### ISSUE TITLE
Citations are not rendering while referencing inside table

### ISSUE THREAD

**Issue by sagarkora** [ismayc/thesisdown#100] opened 2020-07-07 03:13 UTC
If you have a citation inside a table - ex: kable, kablextra, LATEX - they are not rendering while knitting the document to pdf. 

Below is the code to reproduce -

```{r}
# create some random text
library(stringi)
some_text <- stri_rand_lipsum(1)
some_text <- substr(some_text, 1, 75)

# create dataframe with some stuff
figpath <- "figure/"
df <- data.frame(
  Citation = c("@R-base", "@R-bookdown"),
  Textfield = c("**Formatted** string<br/> -- _Everyone_ needs H^2^O", some_text),
  URL = c("[R-url](https://www.r-project.org/)", "[bookdown](https://bookdown.org/)"),
```

```{r kableExtra-table, echo=FALSE, out.width='90%', fig.align = "center", results='asis'}
library(kableExtra)
# http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf 
kable(
  df,
  caption = "kableExtra table: markdown styling works in HTML (*italics*, **bold**), LaTex styling in PDF (\\textbf{bold})",
  booktabs = T, 
  #output_format = "markdown", # output_format = latex, html (specify above)
  # align = "l", 
  valign = "top"
) %>% 
  kable_styling(full_width = F,
                latex_options = c(#"striped",
                  "hold_position", # stop table floating
                  "repeat_header") # for long tables
  ) %>% 
  column_spec(1, bold = T, border_right = T, width = "3em") %>%
  column_spec(2, width = "5em") %>%
  column_spec(3, width = "0.5em") %>%
  footnote(general = "Here is a general comments of the table. ",
           number = c("Footnote 1; ", "Footnote 2; "),
           alphabet = c("Footnote A; ", "Footnote B; "),
           symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
           general_title = "General: ", number_title = "Type I: ",
           alphabet_title = "Type II: ", symbol_title = "Type III: ",
           footnote_as_chunk = T, title_format = c("italic", "underline")
  )
```

Include the bib file and knit the document.

**Comment by ismayc** [comment] 2020-07-07 16:18
I didn't try it directly with {thesisdown} but it should work since {thesisdown} is built on top of {bookdown}. Can you unzip this and try out the Rmd file and let me know if it still isn't working for you? My outputted PDF is also in the ZIP.

[citation-table-pdf_document2.zip](https://github.com/ismayc/thesisdown/files/4885953/citation-table-pdf_document2.zip)

**Comment by sagarkora** [comment] 2020-07-07 18:43
It worked. Looks like the output parameter in the YAML has to be bookdown::pdf_document2. 

However, If I add a couple more columns to the dataframe, the columns are overlapping. I tried to change the width using column_spec, it didn't work. 

To reproduce - add a couple more columns by copying the existing columns in the data frame. I attached the output file.
[citation-table-pdf_document2.pdf](https://github.com/ismayc/thesisdown/files/4886593/citation-table-pdf_document2.pdf)

Landscape orientation doesn't work too.

**Comment by ismayc** [comment] 2020-07-07 18:49
Just to confirm, what error are you seeing when you copy the content I sent you (aside from the YAML) into a file with `thesisdown::thesis_pdf` as the output option? Happy to look into your other question, but I want to make sure this is {thesisdown} specific first and not an issue with a different package.

**Comment by sagarkora** [comment] 2020-07-07 20:04
I didn't see an error. The pdf just renders fine. Attached, please find the project.
[thesisdown.zip](https://github.com/ismayc/thesisdown/files/4886922/thesisdown.zip)

**Comment by ismayc** [comment] 2020-07-08 03:54
Thanks much for confirming. I have a busy next few days ahead but will dig further into your other question as soon as I can.

**Comment by ismayc** [comment] 2020-07-13 01:28
It looks like this is an issue for {kableExtra}. If you set the `format = "markdown"` in `kableExtra::kable()`, then you aren't able to use `kableExtra::landscape()` or get `kableExtra::column_spec()` to work. If you switch it to `format = "latex"` you can get those to work, but then all of the formatting of the references and links break in the outputted table. I tried to force LaTeX citations by switching `Citation = c("@R-base", "@R-bookdown")` to `Citation = c("\\cite{R-base}", "\\cite{R-bookdown}")` but that doesn't work either in generating the reference link. 

I'm going to close this issue since this isn't {thesisdown} specific, but please do keep me updated if {kableExtra} is updated or if your question is better addressed there. I recommend sending them an example using `bookdown::pdf_document2` for when you share your reproducible example of the issue there. Good luck!

**Closed by ismayc** 2020-07-13 01:28 UTC
